### ISSUE TITLE
Include \r in the mqtt message

### ISSUE THREAD

**Issue by helpme1** [mindhelix/mqtt-cli#13]
I would like to publish a message with \r carriage return character inside. Below is what I did.

mqtt-cli mqtt.test.com topic "mqtt_msg 1\r"

However, the carriage return character is not sent. Instead, the ASCII "\r" characters are sent. How can I put the \r carriage return inside the mqtt message?

I am using Windows 10

**Comment by jinmatt** [comment]
try `mqtt-cli mqtt.test.com topic "mqtt_msg 1\\r"`

**Comment by tonight-halfmoon** [comment]
I did not work from Java code. Please advise.
